# Generated by Django 3.2.2 on 2021-06-11 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poza', models.IntegerField()),
                ('etapa', models.CharField(choices=[('REPRODUCTORA', 'Reproductora'), ('RECRIA', 'Recria'), ('ENGORDE', 'Engorde')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('raza', models.CharField(choices=[('INTI', 'Inti')], max_length=50)),
                ('machos', models.IntegerField()),
                ('hembras', models.IntegerField()),
                ('peso_promedio', models.FloatField(blank=True)),
                ('cantidad_gazapos', models.IntegerField(blank=True)),
                ('cuyes_muertos', models.IntegerField(blank=True)),
                ('numero_galpon', models.IntegerField()),
                ('actual', models.BooleanField(default=True)),
                ('fecha_termino', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_real', models.DateField(blank=True)),
                ('fecha_probable', models.DateField()),
                ('poza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozas.poza')),
            ],
        ),
    ]
